name: Nginx docker deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/asokolova/nginx-docker
            git pull origin main
            docker compose up -d --build
            # Если нужно перезапустить докер при обновлении:
            # /usr/local/bin/docker-compose up -d --build reporter
