version: '3.8'

services:
  # 1. База данных
  db:
    image: mariadb:latest
    container_name: nginx-docker-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT}
      - MYSQL_DATABASE=${DB}
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASSWORD_USER}
    volumes:
      - ./db_data:/var/lib/mysql

  # 2. Обработчик PHP
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: nginx-docker-php-
    restart: always
    volumes:
      - ./html/www/landing:/var/www/html/landing
      - ./html/www/social:/var/www/html/social

  # 3. Веб-сервер Nginx
  web:
    build: .
    container_name: nginx-docker-web-
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html/www/landing:/var/www/html/landing
      - ./html/www/social:/var/www/html/social
      - ./conf/landing.conf:/etc/nginx/conf.d/landing.conf
      - ./.htpasswd:/etc/nginx/.htpasswd
      #- /dev/null:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  #Telegram-прокси
  tg-proxy:
    image: telegrammessenger/proxy:latest
    container_name: mtp-proxy
    restart: always
    ports:
      - "8443:443"
    environment:
      - SECRET=${TG_PROXY_SECRET}
      - IP=80.74.25.3
      - WORKERS=4
      - EXTRA_FLAGS=--ipv4-only
  netdata:
    image: netdata/netdata:v1.35.0
    container_name: netdata
    restart: always
    ports:
      - "19999:19999"
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
     # - ./netdata/config:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=${GRAFANA_URL}
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    expose:
      - 3000

volumes:
  prometheus_data:
  grafana_data: