[Interface]
PrivateKey = MLkVG19a2lVOT33g6ZKSO6mClppOUziheX0z21sqgl8=
Address = 10.8.0.8/24
DNS = 1.1.1.1

[Peer]
PublicKey = WIzu+T99C/GRybR6Y+bTJ3i9IdpIAl3UiKYY+LW8Lh8=
Endpoint = 80.74.25.3:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 20