[Interface]
PrivateKey = 2GuteeCBpUvVr0XUaiTSyijA1ZqlDJPjLwszPNjJ+Fg=
Address = 10.8.0.7/24
DNS = 1.1.1.1

[Peer]
PublicKey = WIzu+T99C/GRybR6Y+bTJ3i9IdpIAl3UiKYY+LW8Lh8=
Endpoint = 80.74.25.3:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 20