server {
    listen 80 default_server; 
    server_name 80.74.25.3 localhost; # Сюда будут заходить люди из интернета

    root /var/www/html/landing;
    index index.php index.html;

location /social {
    alias /var/www/html/social; # Говорим Nginx брать файлы отсюда
    index index.php;

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_param SCRIPT_FILENAME $request_filename; # Важно для alias!
        fastcgi_pass php:9000;
    }
}

    # Подключаем обработку PHP
	location = /admin.php {
    auth_basic "Секретная зона";
    auth_basic_user_file /etc/nginx/.htpasswd;

    include snippets/fastcgi-php.conf;
    fastcgi_pass php:9000; 
}
    location /grafana/ {
        proxy_pass http://grafana:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
	

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass php:9000;
    }

  location / {
        try_files $uri $uri/ =404;
    }

}
