version = 5.5.0
archive_dir = /etc/letsencrypt/archive/asokolova.pro
cert = /etc/letsencrypt/live/asokolova.pro/cert.pem
privkey = /etc/letsencrypt/live/asokolova.pro/privkey.pem
chain = /etc/letsencrypt/live/asokolova.pro/chain.pem
fullchain = /etc/letsencrypt/live/asokolova.pro/fullchain.pem
[renewalparams]
account = 06b64a8f682858eb5b9d61b85fe8c4fc
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
asokolova.pro = /var/www/certbot
www.asokolova.pro = /var/www/certbot
[acme_renewal_info]
ari_retry_after = 2026-04-29T19:24:00
